name: Made Richard
favicon: null
layout_spectrum: 0.24524
typography_spectrum: 0.9210199597291648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.997854677727446
  lightness: 0.625
  saturation: 0.5108814623672515
  rhythmicContrast: 0.28480102168396115
purpose: []
